### ISSUE TITLE
Pick License

### ISSUE THREAD

**Issue by nchristensen** [SealUofI/SemPy#2]
I suggest Apache 2.0.

**Comment by thilinarmtb** [comment]
Yeah that sounds fine. Looks like it is the same as BSD, MIT but with some protection
against patent trolls. Can you please add the license to the repo?

**Comment by nchristensen** [comment]
Apparently Apache 2.0 is not compatible with GPLv2 without adding an exception clause so perhaps BSD or MIT would be better. Nek5000 uses BSD-3 so maybe we should stick with that.

@Alexey-Voronin, some of your code is in this repository. Are you okay with a BSD-3 or MIT license?

**Comment by thilinarmtb** [comment]
I am fine with BSD-3.

**Comment by Alexey-Voronin** [comment]
I will defer to @thilinarmtb on this.

**Comment by nchristensen** [comment]
Added BSD-3 license
